### ISSUE TITLE
niepoprawne formatowanie nagłówka

### ISSUE THREAD

**Issue by maciejdzierzek** [peetereczek/ztm-stop-card#5]
Hej, mam "ZTM N37 from 3009 02" zamiast Wilanowska 02 (czy coś takiego) w nagłówku.

**Comment by peetereczek** [comment]
Spróbuj zrobić manualny override wartości sensora, dodaj friendly_name w customize.yaml

**Comment by DarS007** [comment]
Qrcze, wdepnąłem w identyczny problem. Też mam ochotę zmienić nazwę sensora ZTM, ale gdy dodaję 'friendly_name' do 'customize.yaml' to sypie mi błędem:
```
Invalid config for [sensor.ztm]: [friendly_name] is an invalid option for [sensor.ztm]. Check: sensor.ztm->friendly_name. 
(See /xxx/yyy/.homeassistant/configuration.yaml, line 858). Please check the docs at https://github.com/peetereczek/ztm
```
Próbowałem w obu miejscach, tzn. głównej definicji i definicji linii ZTM (na razie skonfigurowałem tylko jedną), ale i jedno, i drugie generuje błąd. Fragment mojego 'configuration.yaml' z zakomentowanymi liniami w obu testowanych lokalizacjach:


```
 - platform: ztm
   api_key: xxx-yyy
## friendly_name: "Przystanek ZZZ"
   lines:
    - number: 508
      stop_id: 3111
      stop_number: "01"
##    friendly_name: "Przystanek ZZZ"

```
Zastanawiam się, jak to debugować dalej...

**Comment by ciompek** [comment]
@DarS007 masz złą konfigurację w configuration.yaml, powinieneś mieć w tym stylu:

```
sensor:
  - platform: ztm
    api_key: XXX
    lines:
      - number: 17
        stop_id: 3286
        stop_number: "03"

homeassistant:       
    customize:
    # Add an entry for each entity that you want to overwrite.
        sensor.ztm_17_from_3286_03:
            friendly_name: "ZTM 17 do Centrum"
```
